#ifndef TINY_OS_SHARED_SYSCALL_KEYBOARD_H
#define TINY_OS_SHARED_SYSCALL_KEYBOARD_H

/*
    功能号：某个按键是否按下
    第一个参数为虚拟键值
*/
#define KEYBOARD_SYSCALL_FUNCTION_IS_KEY_PRESSED 0

#endif /* TINY_OS_SHARED_SYSCALL_KEYBOARD_H */
